chore: target Apple Silicon Macs

diff --git a/install/mac/setup b/install/mac/setup
--- a/install/mac/setup
+++ b/install/mac/setup
@@ -22,10 +22,8 @@ fi
 
 if [[ -x /opt/homebrew/bin/brew ]]; then
 	eval "$(/opt/homebrew/bin/brew shellenv)"
-elif [[ -x /usr/local/bin/brew ]]; then
-	eval "$(/usr/local/bin/brew shellenv)"
 else
-	printf '%s\n' 'Homebrew installation failed.' >&2
+	printf '%s\n' 'Homebrew installation failed or this Mac is not using Apple Silicon.' >&2
 	exit 1
 fi
 
